version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-2019-express
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express 
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS 
      - DB_NAME=sample
    volumes:
      - ./docker/sqlserver/data:/var/opt/mssql/data
      - ./docker/sqlserver/log:/var/opt/mssql/log
      - ./docker/sqlserver/secrets:/var/opt/mssql/sec